# Professional service, newest first.
- years: "2026"
  title: Local Arrangements Chair, ACM UIST 2026

- years: "2021–2026"
  title: Reviewer for IMWUT, UbiComp/ISWC, CHI, ICMI, IEEE VR, and VRST

- years: "2021"
  title: Student Volunteer, ACM MobileHCI, IEEE World Haptics Conference, and ACM IMX
